Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
n_train, n_covariates = scaled_Xtr.shape
kernel = jk.kernels.RBF(active_dims=list(range(n_covariates)))
prior = gpx.Prior(kernel=kernel)

likelihood = gpx.Gaussian(num_datapoints=n_train)

posterior = prior * likelihood
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 2[0m
[1;32m      1[0m n_train, n_covariates [38;5;241m=[39m scaled_Xtr[38;5;241m.[39mshape
[0;32m----> 2[0m kernel [38;5;241m=[39m [43mjk[49m[38;5;241;43m.[39;49m[43mkernels[49m[38;5;241m.[39mRBF(active_dims[38;5;241m=[39m[38;5;28mlist[39m([38;5;28mrange[39m(n_covariates)))
[1;32m      3[0m prior [38;5;241m=[39m gpx[38;5;241m.[39mPrior(kernel[38;5;241m=[39mkernel)
[1;32m      5[0m likelihood [38;5;241m=[39m gpx[38;5;241m.[39mGaussian(num_datapoints[38;5;241m=[39mn_train)

[0;31mAttributeError[0m: module 'jaxkern' has no attribute 'kernels'
AttributeError: module 'jaxkern' has no attribute 'kernels'

